name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

    - name: Build the image
      run: docker build -t bobinaki/dotnettemplate:latest -t bobinaki/dotnettemplate:${{github.sha}} .

    - name: Login to docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 

    - name: Push to Github latest
      run: docker push bobinaki/dotnettemplate:latest

    - name: Push to Github hash commit
      run: docker push bobinaki/dotnettemplate:${{github.sha}}
